springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/FirefighterSchedule
#    url: jdbc:postgresql://ep-solitary-sunset-549677.eu-central-1.aws.neon.tech/FirefighterSchedule?user=michalpuzon&password=tTBE9mHrKSe7
    driverClassName: org.postgresql.Driver
    password: '12345'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
  port: 8081
