springdoc:
  api-docs:
    path: /api-docs
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/FirefighterSchedule
    driverClassName: org.postgresql.Driver
    password: '12345'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
  port: 8081
